### ISSUE TITLE
Qbitorrent origin missmatch.

### ISSUE THREAD

**Issue by jobrien2001** [piperun/torrent-clipper#5]
**Describe the bug**
Qbitorrent has "Cross-Site Request Forgery (CSRF) protection" to prevent people form stealing cookies.  If I disable that, the extension works but i lose protection.  Otherwise I get the following error.

`(W) 2020-05-04T22:06:02 - WebUI: Origin header & Target origin mismatch! Source IP: '::ffff:192.168.1.228'. Origin header: 'chrome-extension://cmhdhpcfabppigjeoienkmleklplflhp'. Target origin: '192.168.1.224:8080'`

My guess  is Origin header & Target origin should be the same?

My guess is 
**Desktop (please complete the following information):**
 - Browser Brave
 - Version 1.8.86 Chromium: 81.0.4044.129 (Official Build) (64-bit)

**Remote torrent client**
 - Client Qbittorent
 - Version v4.2.5

**Comment by piperun** [comment]
This has been fixed in 0.2.12.
