### ISSUE TITLE
Newest version (0.2.12) broke context menu (right click) functionality with qBittorrent 4.2.5 

### ISSUE THREAD

**Issue by kabutocub** [piperun/torrent-clipper#8]
I'm unable to send any torrents through the right-click context menu options to the qBittorrent client.

Furthermore, if "Catch Torrent URLs" option is enabled I am still getting the following error message:

Requests to the server have been blocked by an extension.
Try disabling your extensions.
ERR_BLOCKED_BY_CLIENT

This happens with or without CSRF protection enabled on the QB client.

EDGE Chromium v84.0.522.39
qBittorent v4.2.5

**Comment by piperun** [comment]
Thanks for the issue!
This part is my fault, I forgot to add `'extraHeaders'` in 0.2.12.
And the "Catch Torrent URLs" error is due to how chrome works, it will function as intended however you'll get a "blocked" error since we technically block it.
